enableDefaultRules = true
ignoreGeneratedHeader = false
confidence = 0.8

[rule.atomic]
[rule.bare-return]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.defer]
[rule.dot-imports]
[rule.empty-block]
[rule.enforce-repeated-arg-type-style]
arguments = ["short"]
[rule.enforce-switch-style]
arguments = ["allowNoDefault"]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-equal]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.use-any]
[rule.use-errors-new]
[rule.use-waitgroup-go]
[rule.var-declaration]
[rule.var-naming]
