---
volumes:
  akvorado-clickhouse-2:
  akvorado-clickhouse-3:
  akvorado-clickhouse-4:

services:
  akvorado-orchestrator:
    environment:
      - AKVORADO_CFG_ORCHESTRATOR_CLICKHOUSE_CLUSTER=akvorado
  clickhouse:
    depends_on:
      - zookeeper
    volumes:
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/cluster-1.xml:/etc/clickhouse-server/config.d/cluster-1.xml
  clickhouse-2:
    extends:
      file: docker-compose.yml
      service: clickhouse
    depends_on:
      - zookeeper
    volumes:
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/cluster-2.xml:/etc/clickhouse-server/config.d/cluster-2.xml
      - akvorado-clickhouse-2:/var/lib/clickhouse
  clickhouse-3:
    extends:
      file: docker-compose.yml
      service: clickhouse
    depends_on:
      - zookeeper
    volumes:
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/cluster-3.xml:/etc/clickhouse-server/config.d/cluster-3.xml
      - akvorado-clickhouse-3:/var/lib/clickhouse
  clickhouse-4:
    extends:
      file: docker-compose.yml
      service: clickhouse
    depends_on:
      - zookeeper
    volumes:
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/cluster-4.xml:/etc/clickhouse-server/config.d/cluster-4.xml
      - akvorado-clickhouse-4:/var/lib/clickhouse
